### ISSUE TITLE
Captcha de google en el registro

### ISSUE THREAD

**Issue by rayo329** [decide-moltres/decide-Auth#35]
Estudiar la posibilidad y viabilidad de introducir un captcha en el formulario de registro, que deba ser rellenado por el usuario que intenta registrarse. En caso de ser posible y viable, proceder a la implementación

**Comment by rayo329** [comment]
Se ha podido introducir un captcha en el login/registro y parece funcionar. Sin embargo todavía no conseguimos que sea obligatorio rellenar el captcha para registrarse.

**Comment by jmvolante** [comment]
Salta la vista amarilla de error al no rellenar el captcha en el registro. Está bien que dé el error pero habría que meter un clean.

**Comment by rayo329** [comment]
No se ha llegado a mergear por problemas de última hora
