### ISSUE TITLE
Implementar traducción a otros idiomas

### ISSUE THREAD

**Issue by jmvolante** [decide-moltres/decide-Auth#72]
Se hará una traducción de las vistas de authentication a otros idiomas

**Comment by Juadevarama** [comment]
Para introducir carpetas para nuevos idiomas poned en terminal:
python3 ./manage.py makemessages --locale [el idioma(es, en, fr)]

Cuando hagáis cambios y queráis probarlos en local hay que poner antes: 
python3 ./manage.py compilemessages
