### ISSUE TITLE
Implementar Auth con redes sociales: Github, Google y Facebook

### ISSUE THREAD

**Issue by rayo329** [decide-moltres/decide-Auth#8]
Debemos implementar un método de login que use los credenciales de las web de twitter, Github, google y facebook

**Comment by Juadevarama** [comment]
No tengo claro como implementar las distintas URL de los sitios ni en que URL.py escribirlos.

**Comment by rayo329** [comment]
Referencia Commit: https://github.com/decide-moltres/decide-Auth/commit/af49ecefd0272d246f646a4f47b116d45ee60e2a

**Comment by rayo329** [comment]
En principio se ha implementado ya el login con facebook, Github y Google. La aplicación todavía no ha sido aceptada por twitter y de momento no se puede probar.

**Comment by rayo329** [comment]
Twitter no ha sido aceptada y no da tiempo. procedemos a dar la issue por finalizada
